// flow-typed signature: 7116f2d8ce4d3d9c400e60721f7b2c72
// flow-typed version: <<STUB>>/appcenter-analytics_v^3.0.2/flow_v0.125.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'appcenter-analytics'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'appcenter-analytics' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'appcenter-analytics/__tests__/Analytics' {
  declare module.exports: any;
}

declare module 'appcenter-analytics/Analytics' {
  declare module.exports: any;
}

declare module 'appcenter-analytics/jest/setup' {
  declare module.exports: any;
}

declare module 'appcenter-analytics/react-native.config' {
  declare module.exports: any;
}

declare module 'appcenter-analytics/scripts/postlink' {
  declare module.exports: any;
}

declare module 'appcenter-analytics/test/AppCenterAnalyticsMock' {
  declare module.exports: any;
}

// Filename aliases
declare module 'appcenter-analytics/__tests__/Analytics.js' {
  declare module.exports: $Exports<'appcenter-analytics/__tests__/Analytics'>;
}
declare module 'appcenter-analytics/Analytics.js' {
  declare module.exports: $Exports<'appcenter-analytics/Analytics'>;
}
declare module 'appcenter-analytics/jest/setup.js' {
  declare module.exports: $Exports<'appcenter-analytics/jest/setup'>;
}
declare module 'appcenter-analytics/react-native.config.js' {
  declare module.exports: $Exports<'appcenter-analytics/react-native.config'>;
}
declare module 'appcenter-analytics/scripts/postlink.js' {
  declare module.exports: $Exports<'appcenter-analytics/scripts/postlink'>;
}
declare module 'appcenter-analytics/test/AppCenterAnalyticsMock.js' {
  declare module.exports: $Exports<'appcenter-analytics/test/AppCenterAnalyticsMock'>;
}
