// flow-typed signature: e7a955370d0751156853901e6f4deb5b
// flow-typed version: <<STUB>>/appcenter-crashes_v^3.0.2/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'appcenter-crashes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'appcenter-crashes' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'appcenter-crashes/Crashes' {
  declare module.exports: any;
}

declare module 'appcenter-crashes/react-native.config' {
  declare module.exports: any;
}

declare module 'appcenter-crashes/scripts/postlink' {
  declare module.exports: any;
}

declare module 'appcenter-crashes/test/AppCenterCrashesMock' {
  declare module.exports: any;
}

// Filename aliases
declare module 'appcenter-crashes/Crashes.js' {
  declare module.exports: $Exports<'appcenter-crashes/Crashes'>;
}
declare module 'appcenter-crashes/react-native.config.js' {
  declare module.exports: $Exports<'appcenter-crashes/react-native.config'>;
}
declare module 'appcenter-crashes/scripts/postlink.js' {
  declare module.exports: $Exports<'appcenter-crashes/scripts/postlink'>;
}
declare module 'appcenter-crashes/test/AppCenterCrashesMock.js' {
  declare module.exports: $Exports<'appcenter-crashes/test/AppCenterCrashesMock'>;
}
