// flow-typed signature: 2f005f9e1eb0c9c2673dd615e742cbe4
// flow-typed version: <<STUB>>/appcenter_v^3.0.2/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'appcenter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'appcenter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'appcenter/__tests__/AppCenter.test' {
  declare module.exports: any;
}

declare module 'appcenter/appcenter-log' {
  declare module.exports: any;
}

declare module 'appcenter/AppCenter' {
  declare module.exports: any;
}

declare module 'appcenter/react-native.config' {
  declare module.exports: any;
}

declare module 'appcenter/scripts/postlink' {
  declare module.exports: any;
}

declare module 'appcenter/test/AppCenterMock' {
  declare module.exports: any;
}

// Filename aliases
declare module 'appcenter/__tests__/AppCenter.test.js' {
  declare module.exports: $Exports<'appcenter/__tests__/AppCenter.test'>;
}
declare module 'appcenter/appcenter-log.js' {
  declare module.exports: $Exports<'appcenter/appcenter-log'>;
}
declare module 'appcenter/AppCenter.js' {
  declare module.exports: $Exports<'appcenter/AppCenter'>;
}
declare module 'appcenter/react-native.config.js' {
  declare module.exports: $Exports<'appcenter/react-native.config'>;
}
declare module 'appcenter/scripts/postlink.js' {
  declare module.exports: $Exports<'appcenter/scripts/postlink'>;
}
declare module 'appcenter/test/AppCenterMock.js' {
  declare module.exports: $Exports<'appcenter/test/AppCenterMock'>;
}
