// flow-typed signature: 6400af980f7e0724c73b98847c0990d0
// flow-typed version: <<STUB>>/array-flatten_v^3.0.0/flow_v0.125.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'array-flatten'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'array-flatten' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'array-flatten/dist.es2015' {
  declare module.exports: any;
}

declare module 'array-flatten/dist.es2015/index.spec' {
  declare module.exports: any;
}

declare module 'array-flatten/dist' {
  declare module.exports: any;
}

declare module 'array-flatten/dist/index.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'array-flatten/dist.es2015/index' {
  declare module.exports: $Exports<'array-flatten/dist.es2015'>;
}
declare module 'array-flatten/dist.es2015/index.js' {
  declare module.exports: $Exports<'array-flatten/dist.es2015'>;
}
declare module 'array-flatten/dist.es2015/index.spec.js' {
  declare module.exports: $Exports<'array-flatten/dist.es2015/index.spec'>;
}
declare module 'array-flatten/dist/index' {
  declare module.exports: $Exports<'array-flatten/dist'>;
}
declare module 'array-flatten/dist/index.js' {
  declare module.exports: $Exports<'array-flatten/dist'>;
}
declare module 'array-flatten/dist/index.spec.js' {
  declare module.exports: $Exports<'array-flatten/dist/index.spec'>;
}
