// flow-typed signature: 92151a8dda6eb72cbb4db0d8cb7a75ea
// flow-typed version: <<STUB>>/assert_v^2.0.0/flow_v0.125.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'assert'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'assert' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'assert/build/assert' {
  declare module.exports: any;
}

declare module 'assert/build/internal/assert/assertion_error' {
  declare module.exports: any;
}

declare module 'assert/build/internal/errors' {
  declare module.exports: any;
}

declare module 'assert/build/internal/util/comparisons' {
  declare module.exports: any;
}

// Filename aliases
declare module 'assert/build/assert.js' {
  declare module.exports: $Exports<'assert/build/assert'>;
}
declare module 'assert/build/internal/assert/assertion_error.js' {
  declare module.exports: $Exports<'assert/build/internal/assert/assertion_error'>;
}
declare module 'assert/build/internal/errors.js' {
  declare module.exports: $Exports<'assert/build/internal/errors'>;
}
declare module 'assert/build/internal/util/comparisons.js' {
  declare module.exports: $Exports<'assert/build/internal/util/comparisons'>;
}
