// flow-typed signature: 84c2b2944f0288f42662468792e1c24a
// flow-typed version: <<STUB>>/eslint-plugin-sorting_v^0.4.1/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-sorting'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-sorting' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-sorting/lib/rules/sort-object-props' {
  declare module.exports: any;
}

declare module 'eslint-plugin-sorting/lib/util/check-ignored-types' {
  declare module.exports: any;
}

declare module 'eslint-plugin-sorting/tests/lib/rules/sort-object-props' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-sorting/index' {
  declare module.exports: $Exports<'eslint-plugin-sorting'>;
}
declare module 'eslint-plugin-sorting/index.js' {
  declare module.exports: $Exports<'eslint-plugin-sorting'>;
}
declare module 'eslint-plugin-sorting/lib/rules/sort-object-props.js' {
  declare module.exports: $Exports<'eslint-plugin-sorting/lib/rules/sort-object-props'>;
}
declare module 'eslint-plugin-sorting/lib/util/check-ignored-types.js' {
  declare module.exports: $Exports<'eslint-plugin-sorting/lib/util/check-ignored-types'>;
}
declare module 'eslint-plugin-sorting/tests/lib/rules/sort-object-props.js' {
  declare module.exports: $Exports<'eslint-plugin-sorting/tests/lib/rules/sort-object-props'>;
}
