// flow-typed signature: e4a1fc14586c3c6d1adb8bc50d8f4823
// flow-typed version: <<STUB>>/node-libs-react-native_v^1.2.0/flow_v0.125.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-libs-react-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-libs-react-native' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-libs-react-native/globals' {
  declare module.exports: any;
}

declare module 'node-libs-react-native/mock/buffer' {
  declare module.exports: any;
}

declare module 'node-libs-react-native/mock/console' {
  declare module.exports: any;
}

declare module 'node-libs-react-native/mock/dns' {
  declare module.exports: any;
}

declare module 'node-libs-react-native/mock/empty' {
  declare module.exports: any;
}

declare module 'node-libs-react-native/mock/net' {
  declare module.exports: any;
}

declare module 'node-libs-react-native/mock/process' {
  declare module.exports: any;
}

declare module 'node-libs-react-native/mock/punycode' {
  declare module.exports: any;
}

declare module 'node-libs-react-native/mock/tls' {
  declare module.exports: any;
}

declare module 'node-libs-react-native/mock/tty' {
  declare module.exports: any;
}

declare module 'node-libs-react-native/mock/vm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-libs-react-native/globals.js' {
  declare module.exports: $Exports<'node-libs-react-native/globals'>;
}
declare module 'node-libs-react-native/index' {
  declare module.exports: $Exports<'node-libs-react-native'>;
}
declare module 'node-libs-react-native/index.js' {
  declare module.exports: $Exports<'node-libs-react-native'>;
}
declare module 'node-libs-react-native/mock/buffer.js' {
  declare module.exports: $Exports<'node-libs-react-native/mock/buffer'>;
}
declare module 'node-libs-react-native/mock/console.js' {
  declare module.exports: $Exports<'node-libs-react-native/mock/console'>;
}
declare module 'node-libs-react-native/mock/dns.js' {
  declare module.exports: $Exports<'node-libs-react-native/mock/dns'>;
}
declare module 'node-libs-react-native/mock/empty.js' {
  declare module.exports: $Exports<'node-libs-react-native/mock/empty'>;
}
declare module 'node-libs-react-native/mock/net.js' {
  declare module.exports: $Exports<'node-libs-react-native/mock/net'>;
}
declare module 'node-libs-react-native/mock/process.js' {
  declare module.exports: $Exports<'node-libs-react-native/mock/process'>;
}
declare module 'node-libs-react-native/mock/punycode.js' {
  declare module.exports: $Exports<'node-libs-react-native/mock/punycode'>;
}
declare module 'node-libs-react-native/mock/tls.js' {
  declare module.exports: $Exports<'node-libs-react-native/mock/tls'>;
}
declare module 'node-libs-react-native/mock/tty.js' {
  declare module.exports: $Exports<'node-libs-react-native/mock/tty'>;
}
declare module 'node-libs-react-native/mock/vm.js' {
  declare module.exports: $Exports<'node-libs-react-native/mock/vm'>;
}
