// flow-typed signature: 578cc37c04c4792c2afc7fb27f656320
// flow-typed version: <<STUB>>/node-rsa_v^1.0.8/flow_v0.125.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-rsa'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-rsa' {
  declare type Scheme =
    | 'pkcs1-private-der'
    | 'pkcs1-private-pem'
    | 'pkcs8-private-der'
    | 'pkcs8-private-pem'
    | 'pkcs1-public-der'
    | 'pkcs1-public-pem'
    | 'pkcs8-public-der'
    | 'pkcs8-public-pem'
    | 'private'
    | 'public'
    | 'private-der'
    | 'public-der'
    | 'pkcs1'
    | 'pkcs1-private'
    | 'pkcs1-der'
    | 'pkcs8'
    | 'pkcs8-private'
    | 'pkcs8-der'
    | 'pkcs1-public'
    | 'pkcs8-public';
  declare type Options = {|
    environment?: 'browser' | 'node',
    encryptionScheme?: 'pkcs1_oaep' | 'pkcs1',
    signingScheme?: 'pkcs1' | 'pss' | 'scheme-hash',
  |};
  declare type Encoding = 'buffer' | 'binary' | 'hex' | 'base64';
  declare class NodeRSA {
    constructor(buffer: Buffer, ?Scheme, ?Options): NodeRSA;

    decrypt(string, ?Encoding): string;
    decryptPrivate(string, ?Encoding): string;
    encrypt(string, ?Encoding, ?Encoding): string;
    encryptPrivate(string, ?Encoding, ?Encoding): string;
  }
  declare module.exports: typeof NodeRSA;
}
