// flow-typed signature: 895c87cae67f00ac0fb9e7527f57cd4d
// flow-typed version: <<STUB>>/react-slot-fill_v^2.0.1/flow_v0.125.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-slot-fill'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-slot-fill' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-slot-fill/lib/rsf.es' {
  declare module.exports: any;
}

declare module 'react-slot-fill/lib/rsf' {
  declare module.exports: any;
}

declare module 'react-slot-fill/rollup.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-slot-fill/lib/rsf.es.js' {
  declare module.exports: $Exports<'react-slot-fill/lib/rsf.es'>;
}
declare module 'react-slot-fill/lib/rsf.js' {
  declare module.exports: $Exports<'react-slot-fill/lib/rsf'>;
}
declare module 'react-slot-fill/rollup.config.js' {
  declare module.exports: $Exports<'react-slot-fill/rollup.config'>;
}
