// flow-typed signature: 8c7b964e52de95e2b887f748891890d7
// flow-typed version: <<STUB>>/react-native-img-cache_vhttps://github.com/Brewskey/react-native-img-cache/flow_v0.125.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-img-cache'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-img-cache' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-img-cache/build' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-img-cache/build/index' {
  declare module.exports: $Exports<'react-native-img-cache/build'>;
}
declare module 'react-native-img-cache/build/index.js' {
  declare module.exports: $Exports<'react-native-img-cache/build'>;
}
