// flow-typed signature: 9d1e84063ed654875378b0ab669c719f
// flow-typed version: <<STUB>>/react-native-nfc-manager_vhttps://github.com/whitedogg13/react-native-nfc-manager/flow_v0.125.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-nfc-manager'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-nfc-manager' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-nfc-manager/ByteParser' {
  declare module.exports: any;
}

declare module 'react-native-nfc-manager/ByteParser.test' {
  declare module.exports: any;
}

declare module 'react-native-nfc-manager/example/AndroidMifareClassic' {
  declare module.exports: any;
}

declare module 'react-native-nfc-manager/example/AndroidTechTestNdef' {
  declare module.exports: any;
}

declare module 'react-native-nfc-manager/example/App' {
  declare module.exports: any;
}

declare module 'react-native-nfc-manager/example/AppIndexV2' {
  declare module.exports: any;
}

declare module 'react-native-nfc-manager/example/AppMultiTech' {
  declare module.exports: any;
}

declare module 'react-native-nfc-manager/example/AppV2' {
  declare module.exports: any;
}

declare module 'react-native-nfc-manager/example/AppV2Apdu' {
  declare module.exports: any;
}

declare module 'react-native-nfc-manager/example/AppV2Iso15693' {
  declare module.exports: any;
}

declare module 'react-native-nfc-manager/example/AppV2Mifare' {
  declare module.exports: any;
}

declare module 'react-native-nfc-manager/example/AppV2Ndef' {
  declare module.exports: any;
}

declare module 'react-native-nfc-manager/example/MultiNdefRecord' {
  declare module.exports: any;
}

declare module 'react-native-nfc-manager/NativeNfcManager' {
  declare module.exports: any;
}

declare module 'react-native-nfc-manager/ndef-lib' {
  declare module.exports: any;
}

declare module 'react-native-nfc-manager/ndef-lib/ndef-text' {
  declare module.exports: any;
}

declare module 'react-native-nfc-manager/ndef-lib/ndef-uri' {
  declare module.exports: any;
}

declare module 'react-native-nfc-manager/ndef-lib/ndef-util' {
  declare module.exports: any;
}

declare module 'react-native-nfc-manager/ndef-lib/ndef-wifi-simple' {
  declare module.exports: any;
}

declare module 'react-native-nfc-manager/ndef.test' {
  declare module.exports: any;
}

declare module 'react-native-nfc-manager/NdefParser' {
  declare module.exports: any;
}

declare module 'react-native-nfc-manager/NdefParser.test' {
  declare module.exports: any;
}

declare module 'react-native-nfc-manager/NfcManager' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-nfc-manager/ByteParser.js' {
  declare module.exports: $Exports<'react-native-nfc-manager/ByteParser'>;
}
declare module 'react-native-nfc-manager/ByteParser.test.js' {
  declare module.exports: $Exports<'react-native-nfc-manager/ByteParser.test'>;
}
declare module 'react-native-nfc-manager/example/AndroidMifareClassic.js' {
  declare module.exports: $Exports<'react-native-nfc-manager/example/AndroidMifareClassic'>;
}
declare module 'react-native-nfc-manager/example/AndroidTechTestNdef.js' {
  declare module.exports: $Exports<'react-native-nfc-manager/example/AndroidTechTestNdef'>;
}
declare module 'react-native-nfc-manager/example/App.js' {
  declare module.exports: $Exports<'react-native-nfc-manager/example/App'>;
}
declare module 'react-native-nfc-manager/example/AppIndexV2.js' {
  declare module.exports: $Exports<'react-native-nfc-manager/example/AppIndexV2'>;
}
declare module 'react-native-nfc-manager/example/AppMultiTech.js' {
  declare module.exports: $Exports<'react-native-nfc-manager/example/AppMultiTech'>;
}
declare module 'react-native-nfc-manager/example/AppV2.js' {
  declare module.exports: $Exports<'react-native-nfc-manager/example/AppV2'>;
}
declare module 'react-native-nfc-manager/example/AppV2Apdu.js' {
  declare module.exports: $Exports<'react-native-nfc-manager/example/AppV2Apdu'>;
}
declare module 'react-native-nfc-manager/example/AppV2Iso15693.js' {
  declare module.exports: $Exports<'react-native-nfc-manager/example/AppV2Iso15693'>;
}
declare module 'react-native-nfc-manager/example/AppV2Mifare.js' {
  declare module.exports: $Exports<'react-native-nfc-manager/example/AppV2Mifare'>;
}
declare module 'react-native-nfc-manager/example/AppV2Ndef.js' {
  declare module.exports: $Exports<'react-native-nfc-manager/example/AppV2Ndef'>;
}
declare module 'react-native-nfc-manager/example/MultiNdefRecord.js' {
  declare module.exports: $Exports<'react-native-nfc-manager/example/MultiNdefRecord'>;
}
declare module 'react-native-nfc-manager/NativeNfcManager.js' {
  declare module.exports: $Exports<'react-native-nfc-manager/NativeNfcManager'>;
}
declare module 'react-native-nfc-manager/ndef-lib/index' {
  declare module.exports: $Exports<'react-native-nfc-manager/ndef-lib'>;
}
declare module 'react-native-nfc-manager/ndef-lib/index.js' {
  declare module.exports: $Exports<'react-native-nfc-manager/ndef-lib'>;
}
declare module 'react-native-nfc-manager/ndef-lib/ndef-text.js' {
  declare module.exports: $Exports<'react-native-nfc-manager/ndef-lib/ndef-text'>;
}
declare module 'react-native-nfc-manager/ndef-lib/ndef-uri.js' {
  declare module.exports: $Exports<'react-native-nfc-manager/ndef-lib/ndef-uri'>;
}
declare module 'react-native-nfc-manager/ndef-lib/ndef-util.js' {
  declare module.exports: $Exports<'react-native-nfc-manager/ndef-lib/ndef-util'>;
}
declare module 'react-native-nfc-manager/ndef-lib/ndef-wifi-simple.js' {
  declare module.exports: $Exports<'react-native-nfc-manager/ndef-lib/ndef-wifi-simple'>;
}
declare module 'react-native-nfc-manager/ndef.test.js' {
  declare module.exports: $Exports<'react-native-nfc-manager/ndef.test'>;
}
declare module 'react-native-nfc-manager/NdefParser.js' {
  declare module.exports: $Exports<'react-native-nfc-manager/NdefParser'>;
}
declare module 'react-native-nfc-manager/NdefParser.test.js' {
  declare module.exports: $Exports<'react-native-nfc-manager/NdefParser.test'>;
}
declare module 'react-native-nfc-manager/NfcManager.js' {
  declare module.exports: $Exports<'react-native-nfc-manager/NfcManager'>;
}
