// flow-typed signature: f0cdeb1da75d8ac6cfdf48593ad5e0e9
// flow-typed version: <<STUB>>/react-native-keyboard-aware-scroll-view_v^0.9.1/flow_v0.125.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-keyboard-aware-scroll-view'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-keyboard-aware-scroll-view' {
  declare type KeyboardAwareScrollViewProps = {|
    children: React$Node,
    keyboardShouldPersistTaps?: 'never' | 'always' | 'handled',
    style?: Object,
  |};
  declare export class KeyboardAwareScrollView extends React$Component<KeyboardAwareScrollViewProps> {}
}
