// flow-typed signature: 9a1fe00a6ed40880deda2dcec30d1948
// flow-typed version: <<STUB>>/react-native-keyboard-aware-scroll-view_v0.3.0/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-keyboard-aware-scroll-view'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-keyboard-aware-scroll-view' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-keyboard-aware-scroll-view/lib/KeyboardAwareFlatList' {
  declare module.exports: any;
}

declare module 'react-native-keyboard-aware-scroll-view/lib/KeyboardAwareListView' {
  declare module.exports: any;
}

declare module 'react-native-keyboard-aware-scroll-view/lib/KeyboardAwareMixin' {
  declare module.exports: any;
}

declare module 'react-native-keyboard-aware-scroll-view/lib/KeyboardAwareScrollView' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-keyboard-aware-scroll-view/index' {
  declare module.exports: $Exports<'react-native-keyboard-aware-scroll-view'>;
}
declare module 'react-native-keyboard-aware-scroll-view/index.js' {
  declare module.exports: $Exports<'react-native-keyboard-aware-scroll-view'>;
}
declare module 'react-native-keyboard-aware-scroll-view/lib/KeyboardAwareFlatList.js' {
  declare module.exports: $Exports<'react-native-keyboard-aware-scroll-view/lib/KeyboardAwareFlatList'>;
}
declare module 'react-native-keyboard-aware-scroll-view/lib/KeyboardAwareListView.js' {
  declare module.exports: $Exports<'react-native-keyboard-aware-scroll-view/lib/KeyboardAwareListView'>;
}
declare module 'react-native-keyboard-aware-scroll-view/lib/KeyboardAwareMixin.js' {
  declare module.exports: $Exports<'react-native-keyboard-aware-scroll-view/lib/KeyboardAwareMixin'>;
}
declare module 'react-native-keyboard-aware-scroll-view/lib/KeyboardAwareScrollView.js' {
  declare module.exports: $Exports<'react-native-keyboard-aware-scroll-view/lib/KeyboardAwareScrollView'>;
}
