// flow-typed signature: 22e2c9128b2858c3159ebf40f19cb233
// flow-typed version: <<STUB>>/react-native-event-source_vhttps://github.com/jlkalberer/react-native-event-source/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-event-source'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-event-source' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-event-source/EventSource' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-event-source/EventSource.js' {
  declare module.exports: $Exports<'react-native-event-source/EventSource'>;
}
declare module 'react-native-event-source/index' {
  declare module.exports: $Exports<'react-native-event-source'>;
}
declare module 'react-native-event-source/index.js' {
  declare module.exports: $Exports<'react-native-event-source'>;
}
