// flow-typed signature: 1f7e718942224a8746c636ec8b89e45d
// flow-typed version: <<STUB>>/react-native-permissions_v^2.1.4/flow_v0.125.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-permissions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-permissions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-permissions/lib/commonjs/constants' {
  declare module.exports: any;
}

declare module 'react-native-permissions/lib/commonjs/contract' {
  declare module.exports: any;
}

declare module 'react-native-permissions/lib/commonjs' {
  declare module.exports: any;
}

declare module 'react-native-permissions/lib/commonjs/module.android' {
  declare module.exports: any;
}

declare module 'react-native-permissions/lib/commonjs/module.ios' {
  declare module.exports: any;
}

declare module 'react-native-permissions/lib/commonjs/module' {
  declare module.exports: any;
}

declare module 'react-native-permissions/lib/commonjs/types' {
  declare module.exports: any;
}

declare module 'react-native-permissions/lib/commonjs/utils' {
  declare module.exports: any;
}

declare module 'react-native-permissions/lib/module/constants' {
  declare module.exports: any;
}

declare module 'react-native-permissions/lib/module/contract' {
  declare module.exports: any;
}

declare module 'react-native-permissions/lib/module' {
  declare module.exports: any;
}

declare module 'react-native-permissions/lib/module/module.android' {
  declare module.exports: any;
}

declare module 'react-native-permissions/lib/module/module.ios' {
  declare module.exports: any;
}

declare module 'react-native-permissions/lib/module/module' {
  declare module.exports: any;
}

declare module 'react-native-permissions/lib/module/types' {
  declare module.exports: any;
}

declare module 'react-native-permissions/lib/module/utils' {
  declare module.exports: any;
}

declare module 'react-native-permissions/mock' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-permissions/lib/commonjs/constants.js' {
  declare module.exports: $Exports<'react-native-permissions/lib/commonjs/constants'>;
}
declare module 'react-native-permissions/lib/commonjs/contract.js' {
  declare module.exports: $Exports<'react-native-permissions/lib/commonjs/contract'>;
}
declare module 'react-native-permissions/lib/commonjs/index' {
  declare module.exports: $Exports<'react-native-permissions/lib/commonjs'>;
}
declare module 'react-native-permissions/lib/commonjs/index.js' {
  declare module.exports: $Exports<'react-native-permissions/lib/commonjs'>;
}
declare module 'react-native-permissions/lib/commonjs/module.android.js' {
  declare module.exports: $Exports<'react-native-permissions/lib/commonjs/module.android'>;
}
declare module 'react-native-permissions/lib/commonjs/module.ios.js' {
  declare module.exports: $Exports<'react-native-permissions/lib/commonjs/module.ios'>;
}
declare module 'react-native-permissions/lib/commonjs/module.js' {
  declare module.exports: $Exports<'react-native-permissions/lib/commonjs/module'>;
}
declare module 'react-native-permissions/lib/commonjs/types.js' {
  declare module.exports: $Exports<'react-native-permissions/lib/commonjs/types'>;
}
declare module 'react-native-permissions/lib/commonjs/utils.js' {
  declare module.exports: $Exports<'react-native-permissions/lib/commonjs/utils'>;
}
declare module 'react-native-permissions/lib/module/constants.js' {
  declare module.exports: $Exports<'react-native-permissions/lib/module/constants'>;
}
declare module 'react-native-permissions/lib/module/contract.js' {
  declare module.exports: $Exports<'react-native-permissions/lib/module/contract'>;
}
declare module 'react-native-permissions/lib/module/index' {
  declare module.exports: $Exports<'react-native-permissions/lib/module'>;
}
declare module 'react-native-permissions/lib/module/index.js' {
  declare module.exports: $Exports<'react-native-permissions/lib/module'>;
}
declare module 'react-native-permissions/lib/module/module.android.js' {
  declare module.exports: $Exports<'react-native-permissions/lib/module/module.android'>;
}
declare module 'react-native-permissions/lib/module/module.ios.js' {
  declare module.exports: $Exports<'react-native-permissions/lib/module/module.ios'>;
}
declare module 'react-native-permissions/lib/module/module.js' {
  declare module.exports: $Exports<'react-native-permissions/lib/module/module'>;
}
declare module 'react-native-permissions/lib/module/types.js' {
  declare module.exports: $Exports<'react-native-permissions/lib/module/types'>;
}
declare module 'react-native-permissions/lib/module/utils.js' {
  declare module.exports: $Exports<'react-native-permissions/lib/module/utils'>;
}
declare module 'react-native-permissions/mock.js' {
  declare module.exports: $Exports<'react-native-permissions/mock'>;
}
