// flow-typed signature: b2b95c9b913bd5d912aab1a532efe8d2
// flow-typed version: <<STUB>>/react-native-app-settings_vhttps://github.com/KrazyLabs/react-native-app-settings/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-app-settings'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-app-settings' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-app-settings/index' {
  declare module.exports: $Exports<'react-native-app-settings'>;
}
declare module 'react-native-app-settings/index.js' {
  declare module.exports: $Exports<'react-native-app-settings'>;
}
