// flow-typed signature: 34ded22a30367dddc6620c51d80fb4c5
// flow-typed version: <<STUB>>/react-native-eject_v^0.1.2/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-eject'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-eject' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-eject/build/eject' {
  declare module.exports: any;
}

declare module 'react-native-eject/eject' {
  declare module.exports: any;
}

declare module 'react-native-eject/react-native.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-eject/build/eject.js' {
  declare module.exports: $Exports<'react-native-eject/build/eject'>;
}
declare module 'react-native-eject/eject.js' {
  declare module.exports: $Exports<'react-native-eject/eject'>;
}
declare module 'react-native-eject/react-native.config.js' {
  declare module.exports: $Exports<'react-native-eject/react-native.config'>;
}
