// flow-typed signature: 18380daf2d6f68ed753fb5d9da738d7c
// flow-typed version: <<STUB>>/react-native-code-push_v^6.2.0/flow_v0.125.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-code-push'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-code-push' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-code-push/AlertAdapter' {
  declare module.exports: any;
}

declare module 'react-native-code-push/CodePush' {
  declare module.exports: any;
}

declare module 'react-native-code-push/logging' {
  declare module.exports: any;
}

declare module 'react-native-code-push/package-mixins' {
  declare module.exports: any;
}

declare module 'react-native-code-push/react-native.config' {
  declare module.exports: any;
}

declare module 'react-native-code-push/request-fetch-adapter' {
  declare module.exports: any;
}

declare module 'react-native-code-push/RestartManager' {
  declare module.exports: any;
}

declare module 'react-native-code-push/scripts/generateBundledResourcesHash' {
  declare module.exports: any;
}

declare module 'react-native-code-push/scripts/getFilesInFolder' {
  declare module.exports: any;
}

declare module 'react-native-code-push/scripts/postlink/android/postlink' {
  declare module.exports: any;
}

declare module 'react-native-code-push/scripts/postlink/ios/postlink' {
  declare module.exports: any;
}

declare module 'react-native-code-push/scripts/postlink/run' {
  declare module.exports: any;
}

declare module 'react-native-code-push/scripts/postunlink/android/postunlink' {
  declare module.exports: any;
}

declare module 'react-native-code-push/scripts/postunlink/ios/postunlink' {
  declare module.exports: any;
}

declare module 'react-native-code-push/scripts/postunlink/run' {
  declare module.exports: any;
}

declare module 'react-native-code-push/scripts/recordFilesBeforeBundleCommand' {
  declare module.exports: any;
}

declare module 'react-native-code-push/scripts/tools/linkToolsAndroid' {
  declare module.exports: any;
}

declare module 'react-native-code-push/scripts/tools/linkToolsIos' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-code-push/AlertAdapter.js' {
  declare module.exports: $Exports<'react-native-code-push/AlertAdapter'>;
}
declare module 'react-native-code-push/CodePush.js' {
  declare module.exports: $Exports<'react-native-code-push/CodePush'>;
}
declare module 'react-native-code-push/logging.js' {
  declare module.exports: $Exports<'react-native-code-push/logging'>;
}
declare module 'react-native-code-push/package-mixins.js' {
  declare module.exports: $Exports<'react-native-code-push/package-mixins'>;
}
declare module 'react-native-code-push/react-native.config.js' {
  declare module.exports: $Exports<'react-native-code-push/react-native.config'>;
}
declare module 'react-native-code-push/request-fetch-adapter.js' {
  declare module.exports: $Exports<'react-native-code-push/request-fetch-adapter'>;
}
declare module 'react-native-code-push/RestartManager.js' {
  declare module.exports: $Exports<'react-native-code-push/RestartManager'>;
}
declare module 'react-native-code-push/scripts/generateBundledResourcesHash.js' {
  declare module.exports: $Exports<'react-native-code-push/scripts/generateBundledResourcesHash'>;
}
declare module 'react-native-code-push/scripts/getFilesInFolder.js' {
  declare module.exports: $Exports<'react-native-code-push/scripts/getFilesInFolder'>;
}
declare module 'react-native-code-push/scripts/postlink/android/postlink.js' {
  declare module.exports: $Exports<'react-native-code-push/scripts/postlink/android/postlink'>;
}
declare module 'react-native-code-push/scripts/postlink/ios/postlink.js' {
  declare module.exports: $Exports<'react-native-code-push/scripts/postlink/ios/postlink'>;
}
declare module 'react-native-code-push/scripts/postlink/run.js' {
  declare module.exports: $Exports<'react-native-code-push/scripts/postlink/run'>;
}
declare module 'react-native-code-push/scripts/postunlink/android/postunlink.js' {
  declare module.exports: $Exports<'react-native-code-push/scripts/postunlink/android/postunlink'>;
}
declare module 'react-native-code-push/scripts/postunlink/ios/postunlink.js' {
  declare module.exports: $Exports<'react-native-code-push/scripts/postunlink/ios/postunlink'>;
}
declare module 'react-native-code-push/scripts/postunlink/run.js' {
  declare module.exports: $Exports<'react-native-code-push/scripts/postunlink/run'>;
}
declare module 'react-native-code-push/scripts/recordFilesBeforeBundleCommand.js' {
  declare module.exports: $Exports<'react-native-code-push/scripts/recordFilesBeforeBundleCommand'>;
}
declare module 'react-native-code-push/scripts/tools/linkToolsAndroid.js' {
  declare module.exports: $Exports<'react-native-code-push/scripts/tools/linkToolsAndroid'>;
}
declare module 'react-native-code-push/scripts/tools/linkToolsIos.js' {
  declare module.exports: $Exports<'react-native-code-push/scripts/tools/linkToolsIos'>;
}
