// flow-typed signature: 226dd1aebb8a6e25ff407afd7c66e19f
// flow-typed version: <<STUB>>/react-native-swipeable-list_v^0.0.9/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-swipeable-list'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-swipeable-list' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-swipeable-list/Swipeable/SwipeableFlatList' {
  declare module.exports: any;
}

declare module 'react-native-swipeable-list/Swipeable/SwipeableRow' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-swipeable-list/index' {
  declare module.exports: $Exports<'react-native-swipeable-list'>;
}
declare module 'react-native-swipeable-list/index.js' {
  declare module.exports: $Exports<'react-native-swipeable-list'>;
}
declare module 'react-native-swipeable-list/Swipeable/SwipeableFlatList.js' {
  declare module.exports: $Exports<'react-native-swipeable-list/Swipeable/SwipeableFlatList'>;
}
declare module 'react-native-swipeable-list/Swipeable/SwipeableRow.js' {
  declare module.exports: $Exports<'react-native-swipeable-list/Swipeable/SwipeableRow'>;
}
