// flow-typed signature: c3cee71bcc5d098160fbab5782ab10d1
// flow-typed version: <<STUB>>/react-native-signalr_v^1.0.6/flow_v0.125.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-signalr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-signalr' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-signalr/src/ajax' {
  declare module.exports: any;
}

declare module 'react-native-signalr/src' {
  declare module.exports: any;
}

declare module 'react-native-signalr/src/jquery-function' {
  declare module.exports: any;
}

declare module 'react-native-signalr/src/signalr-jquery-polyfill' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-signalr/index' {
  declare module.exports: $Exports<'react-native-signalr'>;
}
declare module 'react-native-signalr/index.js' {
  declare module.exports: $Exports<'react-native-signalr'>;
}
declare module 'react-native-signalr/src/ajax.js' {
  declare module.exports: $Exports<'react-native-signalr/src/ajax'>;
}
declare module 'react-native-signalr/src/index' {
  declare module.exports: $Exports<'react-native-signalr/src'>;
}
declare module 'react-native-signalr/src/index.js' {
  declare module.exports: $Exports<'react-native-signalr/src'>;
}
declare module 'react-native-signalr/src/jquery-function.js' {
  declare module.exports: $Exports<'react-native-signalr/src/jquery-function'>;
}
declare module 'react-native-signalr/src/signalr-jquery-polyfill.js' {
  declare module.exports: $Exports<'react-native-signalr/src/signalr-jquery-polyfill'>;
}
