// flow-typed signature: 610d273e2a6601b6e047afef1f8c57d6
// flow-typed version: <<STUB>>/react-native-push-notification_v^3.1.1/flow_v0.125.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-push-notification'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-push-notification' {
  declare type RawNotification = {|
    alert?: any,
    color?: string,
    custom_notification?: string,
    data: Object,
    finish: () => void,
    foreground?: boolean,
    id: string,
    message?: string,
    title?: string,
    userInteraction?: false,
  |};
  declare type RegisterResultType = {|
    os: 'android' | 'ios',
    token: string,
  |};
  declare type ConfigureType = {|
    onNotification: (RawNotification) => void,
    onRegister: (RegisterResultType) => void,
    requestPermissions?: boolean,
    senderID: string,
  |};
  declare export default class PushNotification {
    static cancelAllLocalNotifications(): void;
    static configure(ConfigureType): void;
  }
}
