require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'brewskey' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'Firebase'
  pod 'Firebase/Messaging'

  rn_path = '../node_modules/react-native'
  rn_maps_path = '../node_modules/react-native-maps'

  pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
  # If you are using React Native <0.54, you will get the following error:
  # "The name of the given podspec `GLog` doesn't match the expected one `glog`"
  # Use the following line instead:
  #pod 'GLog', :podspec => "#{rn_path}/third-party-podspecs/GLog.podspec"
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"

  # react-native-maps dependencies
  pod 'react-native-maps', path: rn_maps_path
  pod 'react-native-google-maps', path: rn_maps_path  # Remove this line if you don't want to support GoogleMaps on iOS
  pod 'GoogleMaps'  # Remove this line if you don't want to support GoogleMaps on iOS
  pod 'Google-Maps-iOS-Utils' # Remove this line if you don't want to support GoogleMaps on iOS

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'
  pod 'RNOpenAppSettings', :path => '../node_modules/react-native-app-settings'
  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'
  pod 'react-native-nfc-manager', :path => '../node_modules/react-native-nfc-manager'
  pod 'react-native-randombytes', :path => '../node_modules/react-native-randombytes'
  
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  # target 'brewskey-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing

  # end

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  pod 'react-native-geolocation', :path => '../node_modules/@react-native-community/geolocation'

  pod 'ReactNativeART', :path => '../node_modules/@react-native-community/art'

  permissions_path = '../node_modules/react-native-permissions/ios'

  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"
  pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary.podspec"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications.podspec"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary.podspec"

  target 'brewskeyTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
    installer.pods_project.targets.each do |target|
      if target.name == 'react-native-google-maps'
        target.build_configurations.each do |config|
          config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
        end
      end
      # if target.name == "React"
      #   target.remove_from_project
      # end
    end
  end
end
